//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Friendly.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FriendlyDBEntities : DbContext
    {
        public FriendlyDBEntities()
            : base("name=FriendlyDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<FieldOfProfession> FieldOfProfessions { get; set; }
        public virtual DbSet<Location> Locations { get; set; }
        public virtual DbSet<Purpose> Purposes { get; set; }
        public virtual DbSet<User_Location_Purpose> User_Location_Purpose { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
