//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Friendly.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Location_Purpose
    {
        public string City { get; set; }
        public string Username { get; set; }
        public string Purposetype { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
    
        public virtual Location Location { get; set; }
        public virtual Purpose Purpose { get; set; }
        public virtual User User { get; set; }
    }
}
