//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Friendly.DBModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FriendlyDBModelContainer : DbContext
    {
        public FriendlyDBModelContainer()
            : base("name=FriendlyDBModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<FieldOfProfession> FieldOfProfessions { get; set; }
        public virtual DbSet<Location> Locations { get; set; }
        public virtual DbSet<Profile_Location_Purpose> Profile_Location_Purpos { get; set; }
        public virtual DbSet<Profile> Profiles { get; set; }
        public virtual DbSet<Purpose> Purposes { get; set; }
    }
}
