//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Friendly.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Profile
    {
        public string email { get; set; }
        public string firstname { get; set; }
        public string lastname { get; set; }
        public string gender { get; set; }
        public Nullable<System.DateTime> birthdate { get; set; }
        public string industry { get; set; }
        public string workplace { get; set; }
        public string profession { get; set; }
        public byte[] picture { get; set; }
        public string hometown { get; set; }
    }
}
