//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Friendly.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Profile_Location_Purpose
    {
        public string city { get; set; }
        public string email { get; set; }
        public string ptype { get; set; }
        public Nullable<System.DateTime> fromdate { get; set; }
        public Nullable<System.DateTime> todate { get; set; }
    
        public virtual Location Location { get; set; }
        public virtual Profile Profile { get; set; }
        public virtual Purpose Purpose { get; set; }
    }
}
